server:
  port: 8888
spring:
  cloud:
    config:
      server:
      #  git:
      #    uri: https://github.com/Timazay/server-configs.git
      #    default-label: main
      #    search-paths: "{application}"

        jdbc:
          sql: SELECT prop_key, value FROM properties WHERE application=? AND profile=? AND label=?

  datasource:
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://db/cloud
  application:
    name: config-server
  profiles:
    active: jdbc
  jpa:
    show-sql: true
  liquibase:
    drop-first: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
